name: CI-CD

on:
  push:
    branches: 
    - main

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests
        run: mvn clean test site
        working-directory: ./ExMock

      - name: Upload artefatos
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ExMock/target/site/


  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Build
        run: mvn clean install
        working-directory: ./ExMock

      - name: Upload artefatos
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: ExMock/target/*.jar

  Send-email:
    name: Send-email
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Run script
        run: sh ./ExMock/scripts/shell.sh
        env:
          RECIPIENT_EMAIL: "edukarp10@gmail.com" 

